sudo: required

services:
  - docker 

before_install:
  - docker build -t  arbazkhn / docker-startup -f Dockerfile.dev .

scripts:
  - docker run  arbazkhn / docker-startup npm run test -- --coverage

